GET http://localhost:8080/person/api/person
Accept: application/xml


###


GET http://localhost:8080/person/api/person?name=Susi

###

GET http://localhost:8080/person/api/person/demo
Accept: application/json

###

GET http://localhost:8080/person/api/person/demo
Accept: application/xml

###

POST http://localhost:8080/person/api/person
Content-Type: application/json

  {
    "dob": "1999-08-21",
    "name": "Haris"
  }

###

